spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/shareit
#    driver-class-name: org.postgresql.Driver
#    username: root
#    password: root
    url: jdbc:h2:mem:shareit
    driver-class-name: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      #ddl-auto: update
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: ci,test

javax.persistence.schema-generation:
  database.action: create
  create-script-source: schema.sql

logging.level:
  ru.practicum.shareit: TRACE
  org.springframework:
    orm:
      jpa: INFO
      jpa.JpaTransactionManager: DEBUG
    transaction: INFO
    transaction.interceptor: TRACE
  org.hibernate:
    type: TRACE