drop table if exists bookings;
drop table if exists items;
drop table if exists users;

create table users (
   id int8 generated by default as identity,
    email varchar(255) unique,
    name varchar(255),
    primary key (id)
);

create table items (
   id int8 generated by default as identity,
    available boolean,
    description varchar(255),
    name varchar(255),
    owner_id int8,
    primary key (id)
);

create table bookings (
   id int8 generated by default as identity,
    start_date timestamp not null,
    end_date timestamp not null,
    status varchar(255),
    booker_id int8,
    item_id int8,
    primary key (id),
    foreign key (booker_id) references users,
    foreign key (item_id) references items
);