drop table if exists bookings;
drop table if exists comments;
drop table if exists users;
drop table if exists items;
drop table if exists requests;

create table users (
    id      int8 generated by default as identity,
    email   varchar(255) not null unique,
    name    varchar(255) not null,
    primary key (id)
);

create table items (
    id          int8 generated by default as identity,
    available   boolean,
    description varchar(1000),
    name        varchar(255),
    owner_id    int8,
    request_id    int8,
    primary key (id)
);

create table comments (
    id          int8 generated by default as identity,
    text        varchar(1000) not null,
    author_id   int8,
    item_id     int8,
    created     timestamp not null,
    primary key (id),
    foreign key (author_id) references users,
    foreign key (item_id) references items
);

create table bookings (
    id          int8 generated by default as identity,
    start_date  timestamp not null,
    end_date    timestamp not null,
    status      varchar(15),
    booker_id   int8,
    item_id     int8,
    primary key (id),
    foreign key (booker_id) references users,
    foreign key (item_id) references items
);

create table requests (
    id          int8 generated by default as identity,
    user_id     int8,
    created     timestamp not null,
    description varchar(1000) not null,
    primary key (id)
);